/// Brazilian Portuguese names for the seeded exercise catalog, keyed by the
/// canonical English name in `ExerciseLibrary`.
///
/// A missing key is not an error: the exercise falls back to its English name.
const Map<String, String> exerciseNamesPt = <String, String>{
  // Chest
  'Bench Press': 'Supino Reto',
  'Incline Bench Press': 'Supino Inclinado',
  'Decline Bench Press': 'Supino Declinado',
  'Dumbbell Fly': 'Crucifixo com Halteres',
  'Push-ups': 'Flexão de Braço',
  'Chest Dips': 'Mergulho nas Paralelas',
  'Machine Chest Press': 'Supino na Máquina',
  'Cable Crossover': 'Crossover na Polia',
  'Pec Deck': 'Voador',

  // Back
  'Pull-up': 'Barra Fixa',
  'Chin-up': 'Barra Fixa Supinada',
  'Barbell Row': 'Remada Curvada com Barra',
  'Dumbbell Row': 'Remada Unilateral com Halter',
  'Lat Pulldown': 'Puxada na Polia Alta',
  'Deadlift': 'Levantamento Terra',
  'T-Bar Row': 'Remada Cavalinho',
  'Seated Cable Row': 'Remada Sentada na Polia',
  'Chest-Supported Row': 'Remada com Peito Apoiado',
  'Straight-Arm Pulldown': 'Puxada com Braços Estendidos',
  'Inverted Row': 'Remada Invertida',
  'Sumo Deadlift': 'Levantamento Terra Sumô',

  // Shoulders
  'Overhead Press': 'Desenvolvimento Militar',
  'Lateral Raise': 'Elevação Lateral',
  'Front Raise': 'Elevação Frontal',
  'Rear Delt Fly': 'Crucifixo Inverso',
  'Arnold Press': 'Desenvolvimento Arnold',
  'Shrugs': 'Encolhimento de Ombros',
  'Face Pull': 'Face Pull',
  'Machine Shoulder Press': 'Desenvolvimento na Máquina',
  'Cable Lateral Raise': 'Elevação Lateral na Polia',
  'Upright Row': 'Remada Alta',

  // Arms
  'Barbell Curl': 'Rosca Direta com Barra',
  'Dumbbell Curl': 'Rosca Alternada com Halteres',
  'Hammer Curl': 'Rosca Martelo',
  'Preacher Curl': 'Rosca Scott',
  'Triceps Pushdown': 'Tríceps na Polia',
  'Overhead Triceps Extension': 'Tríceps Testa Acima da Cabeça',
  'Triceps Dips': 'Mergulho para Tríceps',
  'Close-Grip Bench Press': 'Supino Fechado',
  'Cable Curl': 'Rosca na Polia',
  'Concentration Curl': 'Rosca Concentrada',
  'Skull Crusher': 'Tríceps Testa',
  'Reverse Curl': 'Rosca Inversa',
  'Wrist Curl': 'Rosca de Punho',

  // Legs
  'Squat': 'Agachamento Livre',
  'Front Squat': 'Agachamento Frontal',
  'Leg Press': 'Leg Press',
  'Leg Extension': 'Cadeira Extensora',
  'Leg Curl': 'Mesa Flexora',
  'Romanian Deadlift': 'Levantamento Terra Romeno',
  'Lunges': 'Afundo',
  'Bulgarian Split Squat': 'Agachamento Búlgaro',
  'Calf Raise': 'Elevação de Panturrilha',
  'Hip Thrust': 'Elevação Pélvica',
  'Hack Squat': 'Agachamento Hack',
  'Goblet Squat': 'Agachamento Goblet',
  'Step-up': 'Step-up',
  'Good Morning': 'Good Morning',
  'Hip Abduction': 'Abdução de Quadril',
  'Hip Adduction': 'Adução de Quadril',
  'Glute Kickback': 'Glúteo Coice',

  // Core
  'Plank': 'Prancha',
  'Crunches': 'Abdominal Supra',
  'Russian Twist': 'Rotação Russa',
  'Leg Raise': 'Elevação de Pernas',
  'Mountain Climbers': 'Escalador',
  'Bicycle Crunches': 'Abdominal Bicicleta',
  'Cable Crunch': 'Abdominal na Polia',
  'Dead Bug': 'Dead Bug',
  'Side Plank': 'Prancha Lateral',
  'Hanging Leg Raise': 'Elevação de Pernas Suspenso',
  'Ab Wheel Rollout': 'Roda Abdominal',
  'Sit-ups': 'Abdominal Completo',
  'Bird Dog': 'Bird Dog',

  // Cardio
  'Running': 'Corrida',
  'Cycling': 'Ciclismo',
  'Rowing': 'Remo Ergométrico',
  'Jump Rope': 'Pular Corda',
  'Walking': 'Caminhada',
  'Elliptical': 'Elíptico',
  'Stair Climber': 'Simulador de Escada',
  'Swimming': 'Natação',

  // Full body
  'Burpees': 'Burpees',
  'Thrusters': 'Thrusters',
  'Clean and Jerk': 'Arremesso',
  'Snatch': 'Arranco',
  'Kettlebell Swing': 'Swing com Kettlebell',
  'Farmer\'s Walk': 'Caminhada do Fazendeiro',
  'Box Jump': 'Salto na Caixa',
  'Battle Ropes': 'Corda Naval',
};
